version: '3.2'

services:
  php-fpm:
    build: ./.docker/php-fpm
    container_name: php-fpm
    entrypoint: ['bash', '/docker-entrypoint.sh']
    command: 'php-fpm'
    volumes:
      - ./:/var/app:rw,cached
    restart: always
    ports:
      - "9000"
    networks:
      - mintos

  nginx:
    build: ./.docker/nginx
    volumes:
      - ./:/var/app
      - ./.docker/nginx/log:/var/log/nginx
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - php-fpm
    networks:
      - mintos

volumes:
  db_data:

networks:
  mintos:
    driver: bridge
